### ISSUE TITLE
Pårørende til ansatt og foresatt til elev

### ISSUE THREAD

**Issue by oleanders** [FINTprosjektet/fint-informasjonsmodell#14]
Må kunne representere foresatte til ansatte i modellen, og må kunne finne foresatte til elever.

Pårørende må ha type som beskriver om det er ektefelle, barn, etc.

**Comment by eidjord** [comment]
Pårørende må ha type som beskriver om det er ektefelle, barn, etc.

**Comment by asgeirn** [comment]
![kontaktperson](https://user-images.githubusercontent.com/58614/39301954-50e3476e-4951-11e8-9d2d-5c1e338d7abf.png)

**Comment by asgeirn** [comment]
![kontaktperson](https://user-images.githubusercontent.com/58614/39303979-5e670752-4958-11e8-9786-7000e764ad09.png)
