### ISSUE TITLE
Problemer med classer som har felter med samme navn

### ISSUE THREAD

**Issue by fsjovatsen** [FINTprosjektet/fint-informasjonsmodell#33]
Vi får problemer med classer som har felter med samme navn i `CS`.

F.eks. classen `Adresse` har et felt ved navn `Adresse`

Vi må ha en regel som sier at man ikke kan ha et feltnavn med samme navn som klassen.

**Comment by fsjovatsen** [comment]
`Adresse` i `Adresse` må fikses umiddelbart.

**Comment by asgeirn** [comment]
Ouch. Men adresse har hatt dette navnet i `1.0.1` også, har det ikke?  I så fall bryter vi bakoverkompatibilitet.

**Comment by asgeirn** [comment]
Hvis vi først skal gjøre noe med `Adresse` vil jeg foreslå å kikke på Postens retningslinjer for adressering. 

- http://www.bring.no/radgivning/sende-noe/klargjoring/klargjoring-adressert/adressering-til-postmottakere-i-norge
-  http://www.bring.no/radgivning/sende-noe/klargjoring/klargjoring-adressert/adressering-til-mottakere-i-utlandet

**Comment by eidjord** [comment]
Ja, vi så på de en gang i tiden, og fant ut at alle de kunne representeres i en adresse(linjer), postnummer, poststed og land. Tror også Bring har en ennå mer detaljert api-definisjon for adresse som vi så på. Men den fant jeg ikke nå i farten.

**Comment by asgeirn** [comment]
Det jeg tenker på er om vi burde modellere det som en `1..*` `Adresselinje` i stedet for en `\n`.

Fra: Ole Anders Eidjord
Sendt: tirsdag 26. september 2017 kl. 09.01
Til: FINTprosjektet/fint-informasjonsmodell
Kopi: Asgeir Storesund Nilsen; Assign
Emne: Re: [FINTprosjektet/fint-informasjonsmodell] Problemer med classersom har felter med samme navn (#33)

Ja, vi så på de en gang i tiden, og fant ut at alle de kunne representeres i en adresse(linjer), postnummer, poststed og land. Tror også Bring har en ennå mer detaljert api-definisjon for adresse som vi så på. Men den fant jeg ikke nå i farten.

**Comment by asgeirn** [comment]
Det jeg tenker på er om vi burde modellere det som en `1..*` `Adresselinje` i stedet for en `\n`.

**Comment by eidjord** [comment]
Enig i det. Muligens den bør stå i flertall: `Adresselinjer`?
