### ISSUE TITLE
Ingen relasjon fra Organisasjonselement til Arbeidsforhold

### ISSUE THREAD

**Issue by asgeirn** [FINTprosjektet/fint-informasjonsmodell#38]
Relasjonen mellom `Arbeidsforhold` og `Organisasjonselement` er enveis, det er ikke mulig å finne alle arbeidsforhold til et organisasjonselement.

**Comment by fsjovatsen** [comment]
Denne haster.

**Comment by oleanders** [comment]
@fsjovatsen Burde vi release det som 2.1.0? Før 2.2.0 med vigo kodeverk?

**Comment by fsjovatsen** [comment]
Jeg mener dette er en bug, så vi kan gjerne release en 2.0.10.

**Comment by asgeirn** [comment]
Fikset i v2.0.10
