### ISSUE TITLE
Flere beskrivelser og felt som bør rettes

### ISSUE THREAD

**Issue by oleanders** [FINTprosjektet/fint-informasjonsmodell#51]
v2.4.0-alpha-1 har følgende, som bør rettes:
- [x] Rette stor `P` i _gyldighetsPeriode_ på _Fullmakt_.
- [x] Mangler en del beskrivelser på felter og relasjoner (Beskjeftigelse, Kontostreng, Tillegg, Lønn, Variabellønn, ...)
- [x] _systemId_ på _Fullmakt_ har engelsk beskrivelse. Endre til norsk.

**Comment by asgeirn** [comment]
Tror jeg fikk med meg alle endringene nå -- ta en titt i branch `feature-salary`.

**Comment by oleanders** [comment]
Ser bra ut @asgeirn! 👏
