### ISSUE TITLE
Leder med personalansvar

### ISSUE THREAD

**Issue by asgeirn** [FINTprosjektet/fint-informasjonsmodell#52]
Informasjonsmodellen kan ikke uttrykke personalansvar, kun leder av organisasjonsenhet.

I tillegg til mangelen dersom personalansvar ikke følger organisasjonsstrukturen gjør det også at konsumenter må ha to regler for å finne en persons leder:

1. Dersom personen ikke er leder selv: Følg relasjon til arbeidssted, og så til leder.
2. Dersom personen selv er leder: Følg relasjon til arbeidssted, så til overordnet, så til leder.

Foreslått løsning: Opprett relasjon mellom `Arbeidsforhold` og `Personalressurs` for personalansvar.

**Comment by oleanders** [comment]
1. Hos oss er det definert at en personalressurs med flere arbeidsforhold har bare en leder med personalansvar (også hvis det er 50% stilling under rektor på en skole, og 50% i sentraladministrasjonen). Er vi sikker på at dette trenger å være på arbeidsforhold?

2. Et annet alternativ til foreslått løsning, er å ha kobling fra arbeidsforhold til organisasjonselement hvor personaleder ligger. For ledere, vil det da typisk peke på nivå over. Dette vil føre til at ikke det skjer en endring på relasjon fra arbeidsforhold, ved endring av leder.

**Comment by asgeirn** [comment]
I release 2.4.0 er det nå en relasjon mellom `Personalressurs` og `Arbeidsforhold` for personalansvar.
