### ISSUE TITLE
Relasjon mellom utdanningforhold og skole

### ISSUE THREAD

**Issue by fsjovatsen** [FINTprosjektet/fint-informasjonsmodell#56]
Denne relasjonen finnes ikke i dag. Bør denne være med?

**Comment by asgeirn** [comment]
Skal relasjonen være til `Elevforhold` eller `Utdanningsforhold` ?

Hvis den knyttes til `Utdanningsforhold` vil også lærere kunne relateres.

Lærere knyttes i dag `Skole` -> `Organisasjonselement` -> `Arbeidsforhold`
