### ISSUE TITLE
Landkode

### ISSUE THREAD

**Issue by fsjovatsen** [FINTprosjektet/fint-informasjonsmodell#6]
* Kan vi bruke iso 3166-1 alpha3?
* Hvor brukes egentlig land?
* Alle land er registrert to gang. En med alpha3 og en med intern nummerisk kode. Det er en referanse fra alpha3 til den nummeriske.
* Hvem bruker landskodene?

**Comment by eidjord** [comment]
1. Ja
2. Landkode er kun i bruk på Adresse og Statsborgerskap (v1.1.0-rc1).
3.  Hvor er de registert to ganger?

**Comment by fsjovatsen** [comment]
VigoKv internt
