### ISSUE TITLE
Poststed

### ISSUE THREAD

**Issue by fsjovatsen** [FINTprosjektet/fint-informasjonsmodell#7]
* Kan vi importere fra posten direkte?

**Comment by eidjord** [comment]
Eller lenke til denne? 
`https://api.bring.com/shippingguide/api/postalCode.json?clientUrl=https://felleskomponent.no&pnr=4770`

Dokumentasjon: [developer.bring.com/api/postal-code](http://developer.bring.com/api/postal-code/)

**Comment by fsjovatsen** [comment]
VigoKV internt
