### ISSUE TITLE
Behøver vi å eksponere PSIGUID_ROW?

### ISSUE THREAD

**Issue by asgeirn** [FINTprosjektet/fint-informasjonsmodell#8]
Den ser ut til å eksponere intern struktur i Vigo Kodeverk, ettersom den inneholder vigok tabellnavn.

Eksempel:

      <PSIGUID_ROW>
        <TABLE_NAME>vigok.grep_kompetansemaal</TABLE_NAME>
        <PSI>f5ada1c0-d588-4c40-a826-976e0ab76823</PSI>
        <GREP_TX_TS>01.06.2015</GREP_TX_TS>
      </PSIGUID_ROW>

**Comment by fsjovatsen** [comment]
Nei
