### ISSUE TITLE
Administrasjon: Lønnsmelding og transaksjonshåndtering

### ISSUE THREAD

**Issue by asgeirn** [FINTprosjektet/fint-informasjonsmodell#89]
https://docs.google.com/document/d/18ySxNFAtCTXjcYON6nFzXeQH-vRjeRTftu0xLQYrBOE/edit?usp=sharing

**Comment by asgeirn** [comment]
![lonn](https://user-images.githubusercontent.com/58614/40774746-ad391a62-64c6-11e8-8d0b-a91b986ab157.png)

**Comment by asgeirn** [comment]
@oleanders

**Comment by oleanders** [comment]
Etter praten med deg gir dette mening @asgeirn
